DjangoWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gensho.urls')),
]

gensho/urls.py
from django.urls import path
from . import views

app_name = 'gensho'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>', views.DetailView.as_view(), name='detail'),
    path('comment/<int:post_pk>', views.CommentView.as_view(), name='comment'),
    path('comment-vote/<int:pk>', views.comment_vote, name='comment_vote'),
    path('post-vote/<int:pk>', views.post_vote, name='post_vote'),
    path('ranking/', views.RankingView.as_view(), name='ranking'),
    path('about/', views.AboutView.as_view(), name='about'),
]

gensho/models.py
from django.db import models
from django.utils import timezone
import pytz
import datetime


class Post(models.Model):
    '''投稿される現象'''

    title = models.CharField('現象', max_length=50, default='Gensho #')
    text = models.TextField('本文')
    post_user = models.CharField('投稿ユーザー名', max_length=50)
    star = models.IntegerField('獲得スター数', default=0)
    created_at = models.DateTimeField('投稿日', auto_now_add=True)

    def __str__(self):
        return self.title + str(self.pk) + ' ' + self.text[:10]

    def get_days_ago(self):
        now = datetime.datetime.now()
        timezones = pytz.timezone('Asia/Tokyo')
        now = timezones.localize(now)
        delta = now - self.created_at
        if (delta.days >= 1):
            return True
        else:
            return False


class Comment(models.Model):
    '''現象に対してつけられるコメント'''

    comment_user = models.CharField('投稿ユーザー名', max_length=50)
    text = models.TextField('本文')
    vote_star = models.IntegerField('獲得スター数', default=0)
    created_at = models.DateTimeField('コメント作成日', auto_now_add=True)
    post = models.ForeignKey(
        Post,
        verbose_name='紐づく現象',
        on_delete=models.PROTECT,
    )

    def __str__(self):
        return self.comment_user

gensho/forms.py
from django import forms
from .models import Comment


class CommentCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Comment
        fields = (
            "comment_user",
            "text",
        )

gensho/views.py
from django.views import generic
from .models import Post, Comment
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
from .forms import CommentCreateForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse


class IndexView(generic.ListView):
    model = Post
    template_name = 'gensho/post_list.html'
    paginate_by = 3

    def get_queryset(self):
        queryset = Post.objects.order_by('-created_at')
        keyword = self.request.GET.get('keyword')  #inputのname
        if keyword:
            queryset = queryset.filter(
                Q(pk__icontains=keyword) | Q(text__icontains=keyword))

        return queryset


def comment_vote(request, pk):
    comments = get_object_or_404(Comment, pk=pk)
    comments.vote_star += 1
    comments.save()
    return redirect(request.META['HTTP_REFERER'])
    #return HttpResponseRedirect(reverse('gensho:detail', args=(Post.pk, )))


def post_vote(request, pk):
    posts = get_object_or_404(Post, pk=pk)
    posts.star += 1
    posts.save()
    return redirect(request.META['HTTP_REFERER'])
    #return HttpResponseRedirect(reverse('gensho:detail', args=(Post.pk, )))


class DetailView(generic.DetailView):
    template_name = 'gensho/post_detail.html'
    model = Post


class CommentView(generic.CreateView):
    template_name = 'gensho/comment_form.html'
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        post_pk = self.kwargs['post_pk']
        comment = form.save(commit=False)
        comment.post = get_object_or_404(Post, pk=post_pk)
        comment.save()
        return redirect('gensho:detail', pk=post_pk)


class RankingView(generic.ListView):
    model = Post
    template_name = 'gensho/ranking_list.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = Post.objects.order_by('-star')
        return queryset


class AboutView(generic.TemplateView):
    template_name = 'gensho/about.html'

gensho/templates/gensho/about.html
{% extends 'gensho/base.html' %}
{% load social_share %}

{% block content %}

    <div class="jumbotron">
        <h1 class="display-3"><strong>What is GENSHO??</strong></h1>
        <p class="lead">GENSHO is Phenomenon Naming Service</p>
        <hr class="my-2">
    </div>

<div class="about">
<div id="toc">
<ul >
<li><a href="#gensho">GENSHO</a></li>
<li><a href="#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95">使用方法</a>
<ul>
<li><a href="#gensho%E3%81%AB%E5%AF%BE%E3%81%97%E3%81%A6%E5%90%8D%E5%89%8D%E3%82%92%E3%81%A4%E3%81%91%E3%82%8B">GENSHOに対して名前をつける</a></li>
<li><a href="#gensho%E8%87%AA%E8%BA%AB%E3%81%ABlike%E3%81%99%E3%82%8B">GENSHO自身に「Like」する</a></li>
<li><a href="#%E6%8A%95%E7%A8%BF%E3%81%95%E3%82%8C%E3%81%9F%E7%8F%BE%E8%B1%A1%E5%90%8D%E3%81%AB%E5%AF%BE%E3%81%97%E3%81%A6%E6%8A%95%E7%A5%A8%E3%81%99%E3%82%8B">投稿された現象名に対して「投票」する</a></li>
</ul>
</li>
<li><a href="#%E4%BB%8A%E5%BE%8C%E3%81%AE%E4%BA%88%E5%AE%9A">今後の予定</a></li>
<li><a href="#%E6%9B%B4%E6%96%B0%E5%B1%A5%E6%AD%B4">更新履歴</a></li>
<li><a href="#q">お問い合わせ</a></li>
</ul>
</div>

<hr>

<h2 id="gensho" class="mb-3">GENSHO</h2>
<p>皆さんはSNS上で度々「〇〇という現象に名前をつけたい」という投稿を見かけないでしょうか．</p>
<p>GENSHOは「そんな明確な名前はついてないけど確かにわかる」という現象に対して勝手に名前をつけていこうではないかというサービスです．</p>
<p>投稿される現象に対して名前をつけ，最も皆に認められた現象名をGENSHOでは今後使用していくことにします．</p>
<p>投稿される現象はSNS上からランダムに取得しています．</p>
<p>ランダムで投稿する関係上，不適切なものがGENSHOとして投稿される可能性があります．</p>
<p>その場合，Twitterのアカウントにて報告していただけますと幸いです．すぐに対処します．</p>
<p>また，<a href="https://twitter.com/tw_gensho" target="blank" rel="noreferrer noopener">Twitterのアカウント</a>に対してDMをすることでGENSHOに投稿依頼をすることができます．</p>
<p>管理者の独断と偏見でDMから採用するGENSHOは決めることをお許しください．</p>

<hr>

<h2 id="%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95" class="mb-3">使用方法</h2>
<p>GENSHOは以下のことを行うことができます．</p>
<ul>
<li>
<p>GENSHOに対して名前をつける</p>
</li>
<li>
<p>GENSHO自身に「Like」する</p>
</li>
<li>
<p>投稿された現象名に対して「投票」する</p>
</li>
</ul>

<hr>

<h3 id="gensho%E3%81%AB%E5%AF%BE%E3%81%97%E3%81%A6%E5%90%8D%E5%89%8D%E3%82%92%E3%81%A4%E3%81%91%E3%82%8B" class="mb-3">GENSHOに対して名前をつける</h3>
<p>GENSHOに対して名前をつけることができます．</p>
<p>ただしGENSHOの投稿から一日までしか命名できません．</p>
<p>また，先着50個までしか反映されません．</p>
<p>投稿する際に名前を書く必要があります．</p>
<p>そのとき，Twitterの@以下を入れていただくことで自動的にTwitterへのリンクが作成されますのでうまく使用してみてください．</p>

<hr>

<h3 id="gensho%E8%87%AA%E8%BA%AB%E3%81%AB%E3%80%8Clike%E3%80%8D%E3%81%99%E3%82%8B" class="mb-3">GENSHO自身に「Like」する</h3>
<p>GENSHOに対してつけられた名前に対してではなく，GENSHO自身に対して「Like」することができます．</p>
<p>これは皆様にとって共感できるGENSHOを見つけるための機能です．</p>
<p>「Ranking」ページでは人気のGENSHOが表示されます．</p>
<p>こんなGENSHOあったよなぁ..と思われた場合は上にある検索欄から調べてください．</p>

<hr>

<h3 id="%E6%8A%95%E7%A8%BF%E3%81%95%E3%82%8C%E3%81%9F%E7%8F%BE%E8%B1%A1%E5%90%8D%E3%81%AB%E5%AF%BE%E3%81%97%E3%81%A6%E3%80%8C%E6%8A%95%E7%A5%A8%E3%80%8D%E3%81%99%E3%82%8B" class="mb-3">投稿された現象名に対して「投票」する</h3>
<p>皆様が投稿された現象名に対して「投票」できます．</p>
<p>ここで一番投票された現象名がそのGENSHOの名前となります．</p>
<p>投票できるのはGENSHOが投稿されてから一日までです．</p>

<hr>

<h2 id="%E4%BB%8A%E5%BE%8C%E3%81%AE%E4%BA%88%E5%AE%9A" class="mb-3">今後の予定</h2>
<ul>
<li>ユーザー登録機能の実装：ランクの導入などを検討</li>
</ul>

<hr>

<h2 id="%E6%9B%B4%E6%96%B0%E5%B1%A5%E6%AD%B4" class="mb-3">更新履歴</h2>
<p>Ver 0.1.0 β版公開</p>
</div>

<hr>

<h2 id="q">お問い合わせ</h2>

<strong><a href="https://twitter.com/tw_gensho" target="blank" rel="noreferrer noopener">Twitter</a></strong> 
{% endblock %}

gensho/templates/gensho/abouts.html
{% extends 'gensho/base.html' %}
{% load social_share %}

{% block content %}
<div class="about mt-3">
<ul >
<li><a href="#gensho">GENSHO</a></li>
<li><a href="#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95">使用方法</a>
<ul>
<li><a href="#gensho%E3%81%AB%E5%AF%BE%E3%81%97%E3%81%A6%E5%90%8D%E5%89%8D%E3%82%92%E3%81%A4%E3%81%91%E3%82%8B">GENSHOに対して名前をつける</a></li>
<li><a href="#gensho%E8%87%AA%E8%BA%AB%E3%81%ABlike%E3%81%99%E3%82%8B">GENSHO自身に「Like」する</a></li>
<li><a href="#%E6%8A%95%E7%A8%BF%E3%81%95%E3%82%8C%E3%81%9F%E7%8F%BE%E8%B1%A1%E5%90%8D%E3%81%AB%E5%AF%BE%E3%81%97%E3%81%A6%E6%8A%95%E7%A5%A8%E3%81%99%E3%82%8B">投稿された現象名に対して「投票」する</a></li>
</ul>
</li>
<li><a href="#%E4%BB%8A%E5%BE%8C%E3%81%AE%E4%BA%88%E5%AE%9A">今後の予定</a></li>
<li><a href="#%E6%9B%B4%E6%96%B0%E5%B1%A5%E6%AD%B4">更新履歴</a></li>
</ul>
<h2 id="gensho" class="mb-3">GENSHO</h2>
<p>皆さんはSNS上で度々「〇〇という現象に名前をつけたい」という投稿を見かけないでしょうか．</p>
<p>GENSHOは「そんな明確な名前はついてないけど確かにわかる」という現象に対して勝手に名前をつけていこうではないかというサービスです．</p>
<p>投稿される現象に対して名前をつけ，最も皆に認められた現象名をGENSHOでは今後使用していくことにします．</p>
<p>投稿される現象はSNS上からランダムに取得しています．</p>
<p>ランダムで投稿する関係上，不適切なものがGENSHOとして投稿される可能性があります．</p>
<p>その場合，Twitterのアカウントにて報告していただけますと幸いです．すぐに対処します．</p>
<p>また，Twitterのアカウントに対してDMをすることでGENSHOに投稿依頼をすることができます．</p>
<p>管理者の独断と偏見でDMから採用するGENSHOは決めることをお許しください．</p>
<h2 id="%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95" class="mb-3">使用方法</h2>
<p>GENSHOは以下のことを行うことができます．</p>
<ul>
<li>
<p>GENSHOに対して名前をつける</p>
</li>
<li>
<p>GENSHO自身に「Like」する</p>
</li>
<li>
<p>投稿された現象名に対して「投票」する</p>
</li>
</ul>
<h3 id="gensho%E3%81%AB%E5%AF%BE%E3%81%97%E3%81%A6%E5%90%8D%E5%89%8D%E3%82%92%E3%81%A4%E3%81%91%E3%82%8B" class="mb-3">GENSHOに対して名前をつける</h3>
<p>GENSHOに対して名前をつけることができます．</p>
<p>ただしGENSHOの投稿から一日までしか命名できません．</p>
<p>また，先着50個までしか反映されません．</p>
<p>投稿する際に名前を書く必要があります．</p>
<p>そのとき，Twitterの@以下を入れていただくことで自動的にTwitterへのリンクが作成されますのでうまく使用してみてください．</p>
<h3 id="gensho%E8%87%AA%E8%BA%AB%E3%81%AB%E3%80%8Clike%E3%80%8D%E3%81%99%E3%82%8B" class="mb-3">GENSHO自身に「Like」する</h3>
<p>GENSHOに対してつけられた名前に対してではなく，GENSHO自身に対して「Like」することができます．</p>
<p>これは皆様にとって共感できるGENSHOを見つけるための機能です．</p>
<p>「Ranking」ページでは人気のGENSHOが表示されます．</p>
<p>こんなGENSHOあったよなぁ..と思われた場合は上にある検索欄から調べてください．</p>
<h3 id="%E6%8A%95%E7%A8%BF%E3%81%95%E3%82%8C%E3%81%9F%E7%8F%BE%E8%B1%A1%E5%90%8D%E3%81%AB%E5%AF%BE%E3%81%97%E3%81%A6%E3%80%8C%E6%8A%95%E7%A5%A8%E3%80%8D%E3%81%99%E3%82%8B" class="mb-3">投稿された現象名に対して「投票」する</h3>
<p>皆様が投稿された現象名に対して「投票」できます．</p>
<p>ここで一番投票された現象名がそのGENSHOの名前となります．</p>
<p>投票できるのはGENSHOが投稿されてから一日までです．</p>
<h2 id="%E4%BB%8A%E5%BE%8C%E3%81%AE%E4%BA%88%E5%AE%9A" class="mb-3">今後の予定</h2>
<ul>
<li>ユーザー登録機能の実装：ランクの導入などを検討</li>
</ul>
<h2 id="%E6%9B%B4%E6%96%B0%E5%B1%A5%E6%AD%B4" class="mb-3">更新履歴</h2>
<p>Ver 0.1.0 β版公開</p>
</div>
{% endblock %}

gensho/templates/gensho/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c|Ubuntu" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'gensho/css/my-css.css' %}">
    <link rel="shortcut icon" href="{% static 'gensho/icon.png' %}">
    <title>GENSHO</title>
  </head>
  <body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'gensho:index' %}">GENSHO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'gensho:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'gensho:about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'gensho:ranking' %}">Ranking</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'gensho:index' %}">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="keyword">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  

      <div class="container">
      {% block content %}
      {% endblock %}
      </div>

    </body>
</html>

gensho/templates/gensho/comment_form.html
{% extends 'gensho/base.html' %}

{% block content %}

<form action="" method='POST'>
{{form.non_field_errors}}
{% for field in form %}
<div class="form-group mt-3" >
    <label for="{{field.id_for_label}}">{{field.label_tag}}</label>
    {{field}}
    {{field.errors}}
</div>
{% endfor %}
{% csrf_token %}
<button type="submit" class="btn btn-primary">送信</button>
</form>

{% endblock %}

gensho/templates/gensho/post_detail.html
{% extends 'gensho/base.html' %}
{% load social_share %}

{% block content %}
<div class="card mb-3 mt-3">
    <h2 class="card-header bg-dark text-white"><a href="{% url 'gensho:detail' post.pk %}">{{post.title}} {{post.pk}} </a><span class="star"><i class="fas fa-star my-orange fa-x"></i> : {{post.star}}</span></h2>
  <div class="card-body">
    <p>{{post.text | linebreaksbr}}</p>
    <p><strong><a href="https://twitter.com/{{post.post_user}}?lang=ja" target="blank" rel="noreferrer noopener">@{{post.post_user}}</a></strong> {{post.created_at}} </p>
    <div class="vote-button">
    <form action="{% url 'gensho:post_vote' post.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Like" name='choice' class="btn btn-primary">
    </form>
    </div>

    <div class="tweet-button">
    {% post_to_twitter "{{post.title}} {{post.pk}}のGENSHOに対して命名しました．" object_or_url "" %}
    </div>
  </div>
</div>

{% if post.comment_set.all.count <= 50 and not post.get_days_ago %}

<a href="{% url 'gensho:comment' post.pk %}" class="btn btn-primary">GENSHO名投稿</a>

{% endif %}

{% if post.get_days_ago %}

{% for comment in post.comment_set.all|dictsort:"vote_star"|slice:":2:-1"  %}

<div class="card mb-3 mt-3">
    <h2 class="card-header bg-success text-white"><a href="https://twitter.com/{{post.post_user}}?lang=ja" target="blank" rel="noreferrer noopener">@{{comment.comment_user}}</a><span class="star"><i class="fas fa-star my-orange fa-x"></i> : {{comment.vote_star}}</span></h2>
  <div class="card-body">
    <p>{{comment.text | linebreaksbr}}   </p>
    <p>{{comment.created_at}}</p>
  </div>
</div>
{% endfor %}

{% for comment in post.comment_set.all|dictsort:"vote_star"|slice:"2::-1"  %}

<div class="card mb-3 mt-3">
    <h2 class="card-header bg-info text-white"><a href="https://twitter.com/{{post.post_user}}?lang=ja" target="blank" rel="noreferrer noopener">@{{comment.comment_user}}</a><span class="star"><i class="fas fa-star my-orange fa-x"></i> : {{comment.vote_star}}</span></h2>
  <div class="card-body">
    <p>{{comment.text | linebreaksbr}}   </p>
    <p>{{comment.created_at}}</p>
  </div>
</div>

{% endfor %}



{% else %}

{% for comment in post.comment_set.all|slice:"::-1"  %}

<div class="card mb-3 mt-3">
    <h2 class="card-header bg-info text-white"><a href="https://twitter.com/{{comment.comment_user}}?lang=ja" target="blank" rel="noreferrer noopener">@{{comment.comment_user}}</a><span class="star"><i class="fas fa-star my-orange fa-x"></i> : {{comment.vote_star}}</span></h2>
  <div class="card-body">
    <p>{{comment.text | linebreaksbr}}   </p>
    <p>{{comment.created_at}}</p>
    <form action="{% url 'gensho:comment_vote' comment.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" value="投票" name='choice' class="btn btn-info">
    </form>
  </div>
</div>
{% endfor %}

{% endif %}

{% endblock %}

gensho/templates/gensho/post_list.html
{% extends 'gensho/base.html' %}
{% load social_share %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-3"><strong>GENSHO</strong></h1>
        <p class="lead">現象にとりあえず名前をつけていくサービス</p>
        <hr class="my-2">
    </div>



{% for post in post_list %}

<div class="card mb-3">
    <h2 class="card-header bg-dark text-white"><a href="{% url 'gensho:detail' post.pk %}">{{post.title}} {{post.pk}} </a><span class="star"><i class="fas fa-star my-orange fa-x"></i> : {{post.star}}</span></h2>
  <div class="card-body">
    <p>{{post.text | linebreaksbr}}</p>
    
    <p class="data"><strong><a href="https://twitter.com/{{post.post_user}}?lang=ja" target="blank" rel="noreferrer noopener">@{{post.post_user}}</a></strong> {{post.created_at}} </p>

    <div class="name-button">
    <a href="{% url 'gensho:detail' post.pk %}" class="btn btn-dark">名前をつける</a>
    </div>

    <div class="vote-button">
    <form action="{% url 'gensho:post_vote' post.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Like" name='choice' class="btn btn-primary">
    </form>
    </div>

    <div class="tweet-button">
    {% post_to_twitter "{{post.title}} {{post.pk}} {{post.text | truncatechars:20}}" object_or_url "" %}
    </div>


    <div class="cf"></div>
    <br><br>
    {% if post.get_days_ago %}
    {% for comment in post.comment_set.all|dictsort:"vote_star"|slice:"0::-1"  %}

  <div class="card mb-3 mt-3">
      <h2 class="card-header bg-success text-white"><a href="https://twitter.com/{{comment.comment_user}}?lang=ja" target="blank" rel="noreferrer noopener">@{{comment.comment_user}}</a><span class="star"><i class="fas fa-star my-orange fa-x"></i> : {{comment.vote_star}}</span></h2>
    <div class="card-body">
      <p>{{comment.text | linebreaksbr}}   </p>
      <p>{{comment.created_at}}</p>
    </div>
  </div>
    
    {% endfor %}
    {% endif %}


  </div>
</div>

{% endfor %}
<div class="parent">
  <div class="center">
{% include 'gensho/page.html' %}
  </div>
</div>
{% endblock %}

gensho/templates/gensho/ranking_list.html
{% extends 'gensho/base.html' %}
{% load social_share %}

{% block content %}

{% for post in post_list %}
<div style="margin-top:30px;"></div>
<div class="card mb-3">
    <h2 class="card-header bg-dark text-white"><a href="{% url 'gensho:detail' post.pk %}">{{post.title}} {{post.pk}} </a><span class="star"><i class="fas fa-star my-orange fa-x"></i> : {{post.star}}</span></h2>
  <div class="card-body">
    <p>{{post.text | linebreaksbr}}</p>
    
    <p class="data"><strong><a href="https://twitter.com/{{post.post_user}}?lang=ja" target="blank" rel="noreferrer noopener">@{{post.post_user}}</a></strong> {{post.created_at}} </p>

    <div class="name-button">
    <a href="{% url 'gensho:detail' post.pk %}" class="btn btn-dark">名前をつける</a>
    </div>

    <div class="vote-button">
    <form action="{% url 'gensho:post_vote' post.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Like" name='choice' class="btn btn-primary">
    </form>
    </div>

    <div class="tweet-button">
    {% post_to_twitter "{{post.title}} {{post.pk}} {{post.text | truncatechars:20}}" object_or_url "" %}
    </div>

    {% if post.get_days_ago %}
    <div class="cf"></div>
    <br><br>
    
    {% for comment in post.comment_set.all|dictsort:"vote_star"|slice:":2:-1"  %}

  <div class="card mb-3 mt-3">
      <h2 class="card-header bg-success text-white"><a href="https://twitter.com/{{comment.comment_user}}?lang=ja" target="blank" rel="noreferrer noopener">@{{comment.comment_user}}</a><span class="star"><i class="fas fa-star my-orange fa-x"></i> : {{comment.vote_star}}</span></h2>
    <div class="card-body">
      <p>{{comment.text | linebreaksbr}}   </p>
      <p>{{comment.created_at}}</p>
    </div>
  </div>
    
    {% endfor %}

    {% endif %}

  </div>
</div>

{% endfor %}



<div class="parent">
  <div class="center">
{% include 'gensho/page.html' %}
  </div>
</div>
{% endblock %}